name: OSS

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  main:
    name: Governance Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@d8b9f7539837ec5e2025aa54541fe88a061ad89e # v3.0.0
        with:
          config-path: .github/labeler.yml
